name: regio_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # COMPATIBILITY FIX: 'PromiseJsImpl' 오류를 해결하기 위해
  # 모든 Firebase 패키지를 최신 안정 버전으로 업데이트합니다.
  firebase_core: ^2.27.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.0
  
  # 이 외의 필수 패키지도 최신 버전으로 맞춥니다.
  firebase_storage: ^11.6.0
  image_picker: ^1.0.8
  intl: ^0.19.0
  
  # iOS 스타일 아이콘을 위한 기본 패키지입니다.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:

  # ⭐️ 바로 이 부분입니다! 
  # 이 줄이 머티리얼 아이콘을 앱에 포함시켜주는 역할을 합니다.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg